INSERT INTO keywords ( name, description ) VALUES ( 'Pre-requisite', 'Must be known before to ensure understanding or use of' );
INSERT INTO keywords ( name, description ) VALUES ( 'Summary', 'summarizes' );
INSERT INTO keywords ( name, description ) VALUES ( 'Background', 'Provides background for' );
INSERT INTO keywords ( name, description ) VALUES ( 'Explanation', 'Explains ' );
INSERT INTO keywords ( name, description ) VALUES ( 'Illustration', 'Provides a graphical representation of' );
INSERT INTO keywords ( name, description ) VALUES ( 'Update', 'Updates or makes more current' );
INSERT INTO keywords ( name, description ) VALUES ( 'Example', 'Provides an example of' );
INSERT INTO keywords ( name, description ) VALUES ( 'Procedure', 'Provides the procedure for an action' );
INSERT INTO keywords ( name, description ) VALUES ( 'Application', 'Contains a theory that is applied in' );
INSERT INTO keywords ( name, description ) VALUES ( 'Purpose', 'Describes the purpose of ' );
INSERT INTO keywords ( name, description ) VALUES ( 'Evidence', 'Provides evidence for' );
INSERT INTO keywords ( name, description ) VALUES ( 'Correction', 'Corrects errors in' );
INSERT INTO keywords ( name, description ) VALUES ( 'Argument', 'Contains the premises of an argument whose conclusions are in' );
INSERT INTO keywords ( name, description ) VALUES ( 'Usage', 'Indicates where, when, or how to invoke an action stated in' );
INSERT INTO keywords ( name, description ) VALUES ( 'Condition', 'A condition that insures the truth of' );
INSERT INTO keywords ( name, description ) VALUES ( 'Warning', 'Warning of undesirable consequences' );
INSERT INTO keywords ( name, description ) VALUES ( 'Solution', 'Contains a solution to a problem posed in' );
INSERT INTO keywords ( name, description ) VALUES ( 'Definition', 'Defines or otherwise restricts meaning of' );
INSERT INTO keywords ( name, description ) VALUES ( 'Comment', 'Gives additional information about' );
INSERT INTO keywords ( name, description ) VALUES ( 'Citation', 'Identifies as the source of concepts and ideas' );
INSERT INTO keywords ( name, description ) VALUES ( 'Content', 'Name what is contained' );
INSERT INTO keywords ( name, description ) VALUES ( 'Alternate view', 'Contains an alternative view to that expressed in' );
INSERT INTO keywords ( name, description ) VALUES ( 'Future', 'Provides an alter to forthcoming work in' );
INSERT INTO keywords ( name, description ) VALUES ( 'Genrealization', 'Makes a generalization about' );
INSERT INTO keywords ( name, description ) VALUES ( 'Causation', 'Describes the cause of' );
INSERT INTO keywords ( name, description ) VALUES ( 'Comparison', 'Is compared to' );
